/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reserve;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextField;

/**
 *
 * @author 심수훈
 */
public class BookInput extends javax.swing.JFrame {

    /**
     * Creates new form BookInput
     */
    public BookInput() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jTextName = new javax.swing.JTextField();
        jTextSex = new javax.swing.JTextField();
        jTextPeoples = new javax.swing.JTextField();
        jTextRoomNum = new javax.swing.JTextField();
        jTextPhoneNum = new javax.swing.JTextField();
        jTextCheckIn = new javax.swing.JTextField();
        jTextPrice = new javax.swing.JTextField();
        jButton_BookOk = new javax.swing.JButton();
        jLabel_UniqueNum = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("성함");

        jLabel2.setText("성");

        jLabel3.setText("인원 수");

        jLabel4.setText("객실 번호");

        jLabel5.setText("전화 번호");

        jLabel6.setText("예상 체크인 시간");

        jLabel7.setText("금액");

        jLabel8.setText("결제 방식");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jTextPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPhoneNumActionPerformed(evt);
            }
        });

        jButton_BookOk.setText("예약 확정");
        jButton_BookOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BookOkActionPerformed(evt);
            }
        });

        jLabel9.setText("체크인 날짜");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addComponent(jLabel_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_BookOk)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextPhoneNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextRoomNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextPeoples, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextSex, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextCheckIn)
                            .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPeoples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_BookOk)
                            .addComponent(jLabel_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    ReserveRoom 에서 받아온 roomNum을 BookInput에 지정하기 위한 setter
    */
    public void setjTextRoomNum(String roomNum) {
        jTextRoomNum.setText(roomNum);
    }

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed

    
    private static String generateUniqueFileName(String[] fileNames) {
        Random random = new Random();
        String uniqueFileName = null;
        boolean isUnique = false;

        while (!isUnique) {
            int randomUnique = random.nextInt(100) + 1;
            uniqueFileName = String.valueOf(randomUnique);
            isUnique = true;

            for (String fileName : fileNames) {
                if (fileName.startsWith(uniqueFileName)) {
                    isUnique = false;
                    
                    break;
                    
                }
            }
        }

        return uniqueFileName;
    }
    
    private String readNameFromFile(String fileName) {
    try {
        File file = new File(fileName);
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line = br.readLine();
        br.close();
        if (line != null) {
            return line.split("/")[0]; // 첫 번째 데이터가 name이므로 해당 값을 반환
        }
    } catch (IOException ex) {
        // 예외 처리
    }
    return null;
}

private String readPhNumFromFile(String fileName) {
    try {
        File file = new File(fileName);
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split("/");
            if (data.length >= 5) {
                return data[4]; // 다섯 번째 데이터가 phNum이므로 해당 값을 반환
            }
        }
        br.close();
    } catch (IOException ex) {
        // 예외 처리
    }
    return null;
}

    
    
    private void jButton_BookOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BookOkActionPerformed
        
 /*
    1. 랜덤 고유번호 생성
    2. 텍스트 필드 값이 비어있지 않을때
    2. 각 텍스트 필드의 값을 가져와서 파일에 저장
    */
     /*
    1. 랜덤 고유번호 생성
    2. 텍스트 필드 값이 비어있지 않을때
    2. 각 텍스트 필드의 값을 가져와서 파일에 저장
    */
    try {
        File allFile = new File("./");
        String[] allFileName = allFile.list();
        
        // 입력 데이터
        String name = jTextName.getText();
        String sex = jTextSex.getText();
        String numOfPpl = jTextPeoples.getText();
        String roomNum = jTextRoomNum.getText();
        String phNum = jTextPhoneNum.getText();
        String checkInTime = jTextCheckIn.getText();
        String checkInDate = jTextDate.getText();
        String roomPrice = jTextPrice.getText();

        // 모든 항목이 입력되었는지 확인
        if (name.isEmpty() || sex.isEmpty() || numOfPpl.isEmpty()
                || roomNum.isEmpty() || phNum.isEmpty() || checkInTime.isEmpty()
                || checkInDate.isEmpty() || roomPrice.isEmpty()) {
            JOptionPane.showMessageDialog(null, "모든 항목을 입력해주세요.");
            return; // 등록 중단
        } else {
            // 중복 예약 확인
            boolean isDuplicate = false;
            for (String fileName : allFileName) {
                String storedName = readNameFromFile(fileName); // 파일에서 저장된 name 가져오기
                String storedPhNum = readPhNumFromFile(fileName); // 파일에서 저장된 phNum 가져오기
                if (storedName != null && storedPhNum != null && storedName.equals(name) && storedPhNum.equals(phNum)) {
                    isDuplicate = true;
                    break;
                }
            }

            if (isDuplicate) {
                JOptionPane.showMessageDialog(null, "이미 예약한 고객입니다.");
                return; // 등록 중단
            }
            
            String uniqueFileName = generateUniqueFileName(allFileName);
            String fileName = uniqueFileName + ".txt";
            File file = new File(fileName);
            BufferedWriter bw = new BufferedWriter(new FileWriter(file, true));

            // 파일에 데이터 입력
            bw.write(name + "/");
            bw.write(sex + "/");
            bw.write(numOfPpl + "/");
            bw.write(roomNum + "/");
            bw.write(phNum + "/");
            bw.write(checkInTime + "/");
            bw.write(checkInDate + "/");
            bw.write(roomPrice + "/");
            String selectedString = (String) jComboBox.getSelectedItem();
            bw.write(selectedString);
            bw.close(); // 파일 입력 완료
            jLabel_UniqueNum.setText("고유번호: "+ uniqueFileName);
            JOptionPane.showMessageDialog(null, "등록 완료");
            setVisible(false);
            new BookFrame().setVisible(true); // 등록 완료 후 메인 화면으로 이동
        }
    } catch (IOException ex) {
        // 예외 처리
    }
    }//GEN-LAST:event_jButton_BookOkActionPerformed

    private void jTextPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPhoneNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInput.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInput.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInput.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInput.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInput().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BookOk;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_UniqueNum;
    private javax.swing.JTextField jTextCheckIn;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPeoples;
    private javax.swing.JTextField jTextPhoneNum;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextRoomNum;
    private javax.swing.JTextField jTextSex;
    // End of variables declaration//GEN-END:variables
}
