/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reserve;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author 심수훈
 */
public class CancelReserve extends javax.swing.JFrame {

    /**
     * Creates new form CancleReserve
     */
    public CancelReserve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButt_Delete = new javax.swing.JButton();
        jText_UniqueNum = new javax.swing.JTextField();
        jButt_Previous = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("고유번호");

        jButt_Delete.setText("삭제");
        jButt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_DeleteActionPerformed(evt);
            }
        });

        jButt_Previous.setText("이전");
        jButt_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_PreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButt_Previous))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jText_UniqueNum, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addComponent(jButt_Delete)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButt_Delete)
                    .addComponent(jText_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButt_Previous)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_DeleteActionPerformed

        // TODO add your handling code here:
        String uniqueNum = jText_UniqueNum.getText();
        String filePath = uniqueNum + ".txt";
        File uniqueFile = new File(filePath);
        
        /*
        고유 번호 입력 - > 삭제
        고유번호가 없으면 없다고 출력
        ***만약 체크인을 한 고객이면 맨끝에 "CHECKIN"이 있을거고
        ***CHECKIN이 있으면 예약 취소가 불가능 하게 해야함
        있으면 해당 고객파일 열어서 4번째 인덱스 (방번호) 가져옴
        cancelReserve(고유번호 , 방번호)
         */
       
        try {
            if (!uniqueFile.exists()) {
                JOptionPane.showMessageDialog(null, "해당 고유번호가 존재하지 않습니다");
            }else{
            FileInputStream fis = new FileInputStream(filePath);
            InputStreamReader isr = new InputStreamReader(fis, "UTF-8");
            BufferedReader uniqueReader = new BufferedReader(isr);

            String[] contents = uniqueReader.readLine().split("/");
            String roomNum = contents[3];
            String isCheckIn = contents[contents.length-1];
            uniqueReader.close();
            if(isCheckIn.equals("CHECKIN")){
            JOptionPane.showMessageDialog(null, "이미 체크인 한 고객입니다 취소할 수 없습니다");
            }else{
            Room room = new Room();
            room.cancelReserve(uniqueNum, roomNum);
            }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButt_DeleteActionPerformed

    private void jButt_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_PreviousActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BookFrame().setVisible(true);
        
    }//GEN-LAST:event_jButt_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelReserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelReserve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButt_Delete;
    private javax.swing.JButton jButt_Previous;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jText_UniqueNum;
    // End of variables declaration//GEN-END:variables
}
