/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reserve;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author 심수훈
 */
public class ReserveRevise extends javax.swing.JFrame {

    /**
     * Creates new form ReserveRevise
     */
    
    /*
    예약 수정 클래스
    1.고유번호로 조회해야함
    2.조회하면 text에 해당 고객의 정보가 뜸
    3.해당 고객의 파일에 정보가 충분하지 않으면 충분하지 않다고 출력
    4.모든 값이 입력 되어 있지 않으면 수정 불가능
    5.해당 고객이 방을 바꿀건지, 방은 그대로 하고 다른 내용만 수정할건지 생각해야함
    6.방을 바꿀거면 Room.txt , ReservedRoom.txt도 수정돼야한다.
    */
    public ReserveRevise() {
        initComponents();
    }

    private String roomNumber;

    public String getRoomNumber() {
        return roomNumber;
    }

    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextCheckIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_BookOk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel_UniqueNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jTextDate = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jTextSex = new javax.swing.JTextField();
        jTextPeoples = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextRoomNum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPhoneNum = new javax.swing.JTextField();
        jButt_Check = new javax.swing.JButton();
        jText_UniqueNum = new javax.swing.JTextField();
        jButt_Previous = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("객실 번호");

        jLabel5.setText("전화 번호");

        jLabel6.setText("예상 체크인 시간");

        jButton_BookOk.setText("예약 확정");
        jButton_BookOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BookOkActionPerformed(evt);
            }
        });

        jLabel7.setText("금액");

        jLabel8.setText("결제 방식");

        jLabel9.setText("체크인 날짜");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));

        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabel1.setText("성함");

        jLabel2.setText("성");

        jLabel3.setText("인원 수");

        jButt_Check.setText("조회");
        jButt_Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_CheckActionPerformed(evt);
            }
        });

        jButt_Previous.setText("이전");
        jButt_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_PreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jText_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextPrice)
                                    .addComponent(jTextCheckIn)
                                    .addComponent(jTextPhoneNum)
                                    .addComponent(jTextRoomNum)
                                    .addComponent(jTextPeoples)
                                    .addComponent(jTextSex)
                                    .addComponent(jTextName)
                                    .addComponent(jLabel_UniqueNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jButton_BookOk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButt_Check)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButt_Previous)))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt_Check)
                    .addComponent(jText_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt_Previous))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPeoples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_BookOk)
                    .addComponent(jLabel_UniqueNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BookOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BookOkActionPerformed

        Room room = new Room();

        String uniqueNum = jText_UniqueNum.getText();
        String fileName = uniqueNum + ".txt";
        try {
            String name = jTextName.getText();
            String sex = jTextSex.getText();
            String numOfPpl = jTextPeoples.getText();
            String newRoomNumber = jTextRoomNum.getText();
            String phNum = jTextPhoneNum.getText();
            String checkInTime = jTextCheckIn.getText();
            String checkInDate = jTextDate.getText();
            String roomPrice = jTextPrice.getText();

            if (name.isEmpty() || sex.isEmpty() || numOfPpl.isEmpty()
                    || newRoomNumber.isEmpty() || phNum.isEmpty() || checkInTime.isEmpty() || checkInDate.isEmpty() || roomPrice.isEmpty()) {
                JOptionPane.showMessageDialog(null, "모든 항목을 입력해주세요.");
                return; // 등록 중단
            } else {
                /*
                room.reserveRoom(roomNum); //방 번호 받아서 다시 예약
                room.cancleReserve(uniqueNum); //룸 되돌리고 , 파일 삭제
                 */
                if (newRoomNumber.equals(roomNumber)) { //방 번호 수정 없는 경우
                    makeUniqueFile(uniqueNum, fileName);
                    JOptionPane.showMessageDialog(null, "수정 완료");
                    setVisible(false);
                    new BookFrame().setVisible(true);
                } else {
                    /*
                    1. ReservedRoom.txt << 해당 방 번호 삭제 후 수정값 추가. (완료)
                    2. ROOM.txt << 기존 예약 방(0)을 roomNum로 변환, 수정값 방을 0으로 변환.
                     */
                    // 1.
                    room.addReservedRoomNum(newRoomNumber);
                    room.removeReservedRoomNum(roomNumber);
                    // 2.
                    room.addRoomNum(roomNumber);
                    room.removeRoomNum(newRoomNumber);

                    makeUniqueFile(uniqueNum, fileName);
                    
                    JOptionPane.showMessageDialog(null, "수정 완료");
                    setVisible(false);
                    new BookFrame().setVisible(true);

                }

            }
        } catch (IOException ex) {
            System.err.println("IOException occurred: " + ex.getMessage());
            ex.printStackTrace(); // 더 많은 정보를 얻기 위해 스택 트레이스 출력
        }
    }//GEN-LAST:event_jButton_BookOkActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNameActionPerformed
    
    /*
    다시 값들을 입력하는 함수
    */
    private void makeUniqueFile(String uniqueNum, String fileName) throws IOException {
        File file = new File(uniqueNum + ".txt");
        BufferedWriter bw = new BufferedWriter(new FileWriter(fileName, false));
        bw.write(jTextName.getText() + "/");
        bw.write(jTextSex.getText() + "/");
        bw.write(jTextPeoples.getText() + "/");
        bw.write(jTextRoomNum.getText() + "/");
        bw.write(jTextPhoneNum.getText() + "/");
        bw.write(jTextCheckIn.getText() + "/");
        bw.write(jTextDate.getText()+"/");
        bw.write(jTextPrice.getText() + "/");
        String selectedString = (String) jComboBox.getSelectedItem();
        bw.write(selectedString);
        bw.close(); //파일 입력됨
    }
    /*
    고유번호 조회하는 함수 "조회" 버튼
    */
    private void jButt_CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_CheckActionPerformed
        // TODO add your handling code here:
        String uniqueNum = jText_UniqueNum.getText();
        String file = uniqueNum + ".txt";
        String filePath = "./" + file;

        // 디렉토리 경로 설정
        String directoryPath = "./";

        // 디렉토리 객체 생성
        File directory = new File(directoryPath);

        // 디렉토리에 있는 파일 이름들 읽어오기
        String[] fileNames = directory.list();
        //System.out.println(Arrays.toString(fileNames)); 테스트용 코드

        ArrayList<String> fileName = new ArrayList<>(Arrays.asList(fileNames)); //fileNames 배열을 ArrayList으로 강제 변환 시키는 함수

        if (!fileName.contains(file)) {
            JOptionPane.showMessageDialog(null, "고유번호를 조회할 수 없습니다");
        } else {
            try {
                FileInputStream fis = new FileInputStream(filePath);
               // InputStreamReader isr = new InputStreamReader(fis, "EUC-KR");
                InputStreamReader isr = new InputStreamReader(fis, "UTF-8");
                BufferedReader br = new BufferedReader(isr);

                String[] text = br.readLine().split("/");
                
                /*
                테스트용 출력 코드
                for (String any : text) {
                    System.out.println(any);
                }
                */
                
                if (text.length < 8) {
                    JOptionPane.showMessageDialog(null, "정보가 불충분합니다");
                } else {
                    jTextName.setText(text[0]);
                    jTextSex.setText(text[1]);
                    jTextPeoples.setText(text[2]);
                    jTextRoomNum.setText(text[3]);
                    jTextPhoneNum.setText(text[4]);
                    jTextCheckIn.setText(text[5]);
                    jTextDate.setText(text[6]);
                    jTextPrice.setText(text[7]);

                    String roomN = jTextRoomNum.getText();
                    setRoomNumber(roomN);
                    br.close();
                }
            } catch (IOException ex) {

            }
        }
    }//GEN-LAST:event_jButt_CheckActionPerformed

    private void jButt_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_PreviousActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BookFrame().setVisible(true);
    }//GEN-LAST:event_jButt_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReserveRevise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReserveRevise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReserveRevise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReserveRevise.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveRevise().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButt_Check;
    private javax.swing.JButton jButt_Previous;
    private javax.swing.JButton jButton_BookOk;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_UniqueNum;
    private javax.swing.JTextField jTextCheckIn;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPeoples;
    private javax.swing.JTextField jTextPhoneNum;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextRoomNum;
    private javax.swing.JTextField jTextSex;
    private javax.swing.JTextField jText_UniqueNum;
    // End of variables declaration//GEN-END:variables
}
