/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Checkin;

import cse.hotelmanagement.MScreen;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author pgr03
 */
public class Checkin1_2 extends javax.swing.JFrame {

    private String fileName; // 파일 이름을 저장하는 필드
    private String userInput;

    public javax.swing.JTextField getTxtName() {     // textName 필드의 값을 반환하는 메서드를 선언
        return textName;     //textName은 사용자가 입력한 이름을 보관하는 텍스트 필드
    }

// 파일 이름을 저장하는 필드
    /**
     * Creates new form Checkin2
     */
    public Checkin1_2() {
        initComponents();
    }

    public Checkin1_2(String fileName) {
        initComponents();
        this.fileName = fileName;
        textNumber.setText(fileName);
    }

    public javax.swing.JTextField getTxtNumber() {  // textNumber 필드의 값을 반환하는 메서드를 선언
        return textNumber;      //textNumber은 사용자가 입력한 번호를 보관하는 텍스트 필드
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_OK = new javax.swing.JButton();
        jButton_NO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("예약된 고객입니다.");

        jButton_OK.setText("예");
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_NO.setText("아니요");
        jButton_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NOActionPerformed(evt);
            }
        });

        jLabel2.setText("님의 고유번호는");

        jLabel3.setText("체크인 하시겠습니까?");

        jLabel6.setText("입니다.");

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        textNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK)
                    .addComponent(jButton_NO))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // Checkin2 화면으로 전환
        Checkin2 checkin2Frame = new Checkin2();
        checkin2Frame.setVisible(true);
        setVisible(false);

        // 파일 읽기
        String fileName = textNumber.getText(); // 파일 이름 가져오기(textNumber 텍스트 필드의 텍스트를 가져와 fileName 변수에 저장)
        String filePath = fileName + ".txt"; // 파일 경로
        File file = new File(filePath); //filePath를 경로로 하는 File 객체를 생성
        
        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line = reader.readLine();
           
            if (line != null) { //읽은 줄이 null이 아닌 경우
                String[] data = line.split("/");    // 읽은 줄을 "/" 문자를 기준으로 분리하고, 분리된 문자열 배열을 'data' 변수에 저장
               
                if (data.length >= 6) { //문자열 배열의 길이가 6 이상인 경우, 즉 필요한 정보가 모두 있는 경우,

                    String name = data[0]; // 배열의 0번째 값(이름) 가져오기
                    String roomNumber = data[3]; // 배열의 3번째 값(객실 번호) 가져오기
                    String date = data[6]; //배열의 6번째 값(체크인 날짜) 가져오기
                    checkin2Frame.getTname().setText(name); // Tname 필드에 이름 설정
                    checkin2Frame.getTRoomnum().setText(roomNumber); // TRoomnum 필드에 객실 번호 설정
                    checkin2Frame.getTdate().setText(date); // Tdate 필드에 날짜 설정
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NOActionPerformed
        new MScreen().setVisible(true);
        setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton_NOActionPerformed

    private void textNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumberActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkin1_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_NO;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNumber;
    // End of variables declaration//GEN-END:variables

}
